{% set name = "mafredo" %}
{% set version = "0.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 097db74a6ac5ede1e995c63d6f059ecac5f1b3aa207f24a53378a378a2263348

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.5
    - pyscaffold
    - setuptools
  run:
    - python >=3.5
    - xarray
    - scipy
    - numpy
    - pyyaml
    
test:
  imports:
    - mafredo

about:
  home: https://github.com/RubendeBruin/mafredo
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: "Marine Frequency Domain"
  doc_url: https://mafredo.readthedocs.io/en/latest/ 
  dev_url: https://github.com/RubendeBruin/mafredo

extra:
  recipe-maintainers:
    - rubendebruin
